#!/usr/bin/fish

if [ "$argv[1]" = "-v" ] || [ "$argv[1]" = "--version" ];
  echo 'UnityX 11' && exit
end

# Change directory to unityx directory
cd (dirname (status -f))

# Set XDG_CURRENT_DESKTOP
export XDG_CURRENT_DESKTOP=UnityX

# Start unityx-settings-daemon
bash settings_daemon/settings_daemon.sh
